<?

/**
 * Implements hook_mail
 */
function mailer_mail($key, &$message, $params)
{
  $front_url = url('<front>', ['absolute' => true]);
  switch($key) {
    case 'manager_notify_query_correction_new':
      $message['subject'] = 'Новая корректировка';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>Новая корректировка на сайте "Управление заказами":</p>' .
        'Номер: ' . $params["qid"] . '<br />' .
        'Месяц: ' . $params["month"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        ($params["comment"] ? 'Комментарий: ' . $params["comment"] . '<br />' : '') .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

    case 'manager_notify_query_cancel_new':
      $message['subject'] = 'Отмена заявки на производство';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>На сайте "Управление заказами" пользователь запросил отмену производства:</p>' .
        'Номер заявки: ' . $params["qid"] . '<br />' .
        'Месяц: ' . $params["month"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        ($params["comment"] ? 'Комментарий: ' . $params["comment"] . '<br />' : '') .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

      case 'client_notify_query_correction_new':
      $message['subject'] = 'Новая корректировка по вашей заявке';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>На сайте компании ООО "Кирово-Чепецкий завод Агрохимикат" <a href="' . $front_url . '">"Управление заказами"</a> внесена корректирующая заявка в план производства на ' . $params['month'] . '. </p>' .
        'Номер заявки: ' . $params["qid"] . '<br />' .
        'Месяц: ' . $params["month"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        'Причина: ' . $params["reason"] .  '<br />' .
        'Требуется согласование: ' . ($params["client_approve"] ? 'да' : 'нет')  .  '<br />' .
        ($params["comment"] ? 'Комментарий: ' . $params["comment"] . '<br />' : '') .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

    case 'client_notify_query_cancel_new':
      $message['subject'] = 'Отмена вашей заявки на производство';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>На сайте компании ООО "Кирово-Чепецкий завод Агрохимикат" <a href="' . $front_url . '">"Управление заказами"</a> отменено производство препарата</p>' .
        'Номер заявки на отмену: ' . $params["qid"] . '<br />' .
        'Месяц: ' . $params["month"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        'Причина: ' . $params["reason"] .  '<br />' .
        'Требуется согласование: ' . ($params["client_approve"] ? 'да' : 'нет')  .  '<br />' .
        ($params["comment"] ? 'Комментарий: ' . $params["comment"] . '<br />' : '') .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

    case 'client_notify_query_handling':
      $message['subject'] = 'Статус заявки на производство изменился';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>На сайте компании ООО "Кирово-Чепецкий завод Агрохимикат" <a href="' . $front_url . '">"Управление заказами"</a> изменился статус заявки.</p>' .
        'Номер заявки: ' . $params["qid"] . '<br />' .
        'Месяц: ' . $params["month"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        'Новый статус: ' . $params["status_manager"] .  '<br />' .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

    case 'manager_notify_query_handling':
      $message['subject'] = 'Статус заявки на производство изменился';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>На сайте "Управление заказами" пользователь изменил статус заявки:</p>' .
        'Номер заявки: ' . $params["qid"] . '<br />' .
        'Месяц: ' . $params["month"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        'Новый статус: ' . $params["status_client"] .  '<br />' .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

    case 'user_notify_plan_import':
      $message['subject'] = 'Импортирован план на ' . $params['month'];
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>На сайте компании ООО "Кирово-Чепецкий завод Агрохимикат" <a href="http://prod.kccc.ru">"Управление заказами"</a> внесён план производства на ' . $params['month'] . '. </p>' .
        '<p>Необходимо до 25 числа проверить свои заявки на производство и принять план или связаться с нашим менеджером для внесения изменений.</p>' .
        '<p>Для принятия плана перейдите на <a href="http://prod.kccc.ru">сайт</a> и нажмите кнопку "Согласовать весь план"</p>';

      break;
  }
}


/**
 * Implements hook_mail_alter
 */
function mailer_mail_alter(&$message)
{
  if (strpos($_SERVER['HTTP_HOST'], '.local') !== FALSE && empty($message["params"]["force_local_send"])) {
    $message['send'] = false;
    watchdog('mailer', 'Эмуляция отправки E-Mail.<br />Почта: ' . $message['to'] . '.<br />Тема: ' . $message['subject'] . '<br />Текст: ' . var_export($message['body'], true), [], WATCHDOG_DEBUG);
  }
}
