<?
/**
 * Implements hook_cron_queue_info().
 */
function mailer_cron_queue_info()
{
  $queues['daily_mails_queue'] = array(
    'worker callback' => 'mailer_send_daily_mails',
  );

  return $queues;
}

/**
 * queue callback
 */
function mailer_send_daily_mails($params)
{
  drupal_mail('mailer', 'client_notify_daily_changes', $params['mail'], 'ru', $params);
}

/**
 * Implements hook_mail
 */
function mailer_mail($key, &$message, $params)
{
  $front_url = url('<front>', ['absolute' => true]);
  switch($key) {
    case 'client_notify_daily_changes':
      $message['subject'] = 'Изменения за прошедшие сутки';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>Сводка с изменениями за последние сутки на сайте "Управление заказами":</p>' .
        $params['text'] .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

      case 'manager_notify_query_correction_new':
      $message['subject'] = 'Новая корректировка';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>Новая корректировка на сайте "Управление заказами":</p>' .
        'Номер: ' . $params["qid"] . '<br />' .
        'Месяц: ' . $params["month"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        ($params["reason"] ? 'Причина: ' . $params["reason"] . '<br />' : '') .
        ($params["comment"] ? 'Комментарий: ' . $params["comment"] . '<br />' : '') .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

//    case 'manager_notify_query_cancel_new':
//      $message['subject'] = 'Отмена заявки на производство';
//      $message['body'][] =
//        '<h2>Здравствуйте!</h2>' .
//        '<p>На сайте "Управление заказами" пользователь запросил отмену производства:</p>' .
//        'Номер заявки: ' . $params["qid"] . '<br />' .
//        'Месяц: ' . $params["month"] . '<br />' .
//        'Продукт: ' . $params["product"] .  '<br />' .
//        ($params["reason"] ? 'Причина: ' . $params["reason"] . '<br />' : '') .
//        ($params["comment"] ? 'Комментарий: ' . $params["comment"] . '<br />' : '') .
//        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';
//
//      break;

    case 'client_notify_query_correction_new':
      $message['subject'] = 'Новая корректировка по вашей заявке';
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>На сайте компании ООО "Кирово-Чепецкий завод Агрохимикат" <a href="' . $front_url . '">"Управление заказами"</a> внесена корректирующая заявка в план производства на ' . $params['month'] . '. </p>' .
        'Номер заявки: ' . $params["qid"] . '<br />' .
        'Месяц: ' . $params["month"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        'Количество: ' . $params["volume"] .  '<br />' .
        (!empty($params["reason"]) ? 'Причина: ' . $params["reason"] . '<br />' : '') .
        (!empty($params["comment"]) ? 'Комментарий: ' . $params["comment"] . '<br />' : '') .
        $params['notification'] .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

    case 'client_notify_wwork_fail':
      $message['subject'] = $params["subject"];
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>' . $params["text"] . '</p>' .
        'Дата и время заявки: ' . $params["datetime"] . ' (<a href="/warehouse/queue?month=' . gmdate('n', $params["wwork_time"]) . '&day=' . gmdate('j', $params["wwork_time"]) . '&year=' . gmdate('Y', $params["wwork_time"]) . '&offset=' . $params["offset"]/60 . '" target="_blank">ссылка</a>)<br />' .
        (!empty($params["truck_number"]) ? '№ автомобиля: ' . $params["truck_number"] .  '<br />' : '') .
        (!empty($params["driver"]) ? 'Водитель: ' . $params["driver"] .  '<br />' : '') .
        (!empty($params["note"]) ? 'Пометки: ' . $params["note"] . '<br />' : '') .
        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';

      break;

//    case 'client_notify_query_handling':
//      $message['subject'] = 'Статус заявки на производство изменился';
//      $message['body'][] =
//        '<h2>Здравствуйте!</h2>' .
//        '<p>На сайте компании ООО "Кирово-Чепецкий завод Агрохимикат" <a href="' . $front_url . '">"Управление заказами"</a> изменился статус заявки.</p>' .
//        'Номер заявки: ' . $params["qid"] . '<br />' .
//        'Месяц: ' . $params["month"] . '<br />' .
//        'Продукт: ' . $params["product"] .  '<br />' .
//        'Новый статус: ' . $params["status_manager"] .  '<br />' .
//        (!empty($params["reason"]) ? 'Причина: ' . $params["reason"] . '<br />' : '') .
//        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';
//
//      break;

//    case 'manager_notify_query_handling':
//      $message['subject'] = 'Статус заявки на производство изменился';
//      $message['body'][] =
//        '<h2>Здравствуйте!</h2>' .
//        '<p>На сайте "Управление заказами" пользователь изменил статус заявки:</p>' .
//        'Номер заявки: ' . $params["qid"] . '<br />' .
//        'Месяц: ' . $params["month"] . '<br />' .
//        'Продукт: ' . $params["product"] .  '<br />' .
//        'Новый статус: ' . $params["status_client"] .  '<br />' .
//        (!empty($params["reason"]) ? 'Причина: ' . $params["reason"] . '<br />' : '') .
//        '<p>Перейти к управлению заявками в <a href="' . $front_url . '">Личный кабинет</a></p>';
//
//      break;

    case 'user_notify_plan_import':
      $message['subject'] = 'Импортирован план на ' . $params['month'];
      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>На сайте компании ООО "Кирово-Чепецкий завод Агрохимикат" <a href="http://prod.kccc.ru">"Управление заказами"</a> внесён план производства на ' . $params['month'] . '. </p>' .
        '<p>Ознакомиться с планом можно в <a href="http://prod.kccc.ru">Личном кабинете</a></p>';

      break;
  }
}


/**
 * Implements hook_mail_alter
 */
function mailer_mail_alter(&$message)
{
  if (strpos($_SERVER['HTTP_HOST'], '.local') !== FALSE || !variable_get('client_email_enable', 1)) {
    $message['send'] = false;
    watchdog('mailer', 'Эмуляция отправки E-Mail.<br />Почта: ' . $message['to'] . '<br />Тема: ' . $message['subject'] . '<br />Текст: ' . var_export($message['body'], true), [], WATCHDOG_DEBUG);
  } else {
    watchdog('mailer', 'Отправка E-Mail.<br />Почта: ' . $message['to'] . '<br />Тема: ' . $message['subject'] . '<br />Текст: ' . var_export($message['body'], true), [], WATCHDOG_DEBUG);
  }
}


/**
 * Собрать все изменения за день в одно письмо
 */
function mailer_batch_mail_production()
{
  // извлечь все пришедшие заявки за прошедние сутки
  $efquery = new EntityFieldQuery();
  $efquery
    ->entityCondition('entity_type', 'query')
    ->propertyCondition('uid', 0)
    ->propertyCondition('created', time(), '<')
    ->propertyCondition('created', time() - 60*60*24, '>=')
    ->propertyOrderBy('id', 'ASC');
  $result = $efquery->execute();
  if (!empty($result['query'])) {

    // разбить по Компаниям
    $queries_by_companies = [];
    foreach ($result['query'] as $query) {
      $query_wr = entity_metadata_wrapper('query', $query->id);
      if ($query_wr->field_nomenklatura->field_user->value()) {
        if ($company_id = $query_wr->field_nomenklatura->field_user->uid->value()) {
          if (empty($queries_by_companies[$company_id])) {
            $queries_by_companies[$company_id] = [
              'queries' => [],
              'company_uid' => $query_wr->field_nomenklatura->field_user->uid->value(),
            ];
          }
          $queries_by_companies[$company_id]['queries'][] = $query;
        }
      }
    }

    // для каждого пользователя составить текст письма и поставить в очередь
    $mail_queue = DrupalQueue::get('daily_mails_queue');
    foreach ($queries_by_companies as $company_id => $value) {

      $main_plan_flag = false;
      $pred_plan_flag = false;
      $params['text'] = '';
      foreach ($value['queries'] as $query) {
        $query_wr = entity_metadata_wrapper('query', $query->id);

        // Уведомления по Установкам
        $notification =  '';
        if ($query_wr->field_query_notifications->count()) {
          $notification =  '<br />ВНИМАНИЕ!<br />';
          foreach($query_wr->field_query_notifications->getIterator() as $notif_wr) {
            $notif_arr[$notif_wr->field_qn_produce_unit->tid->value()] = [
              'name' => $notif_wr->field_qn_produce_unit->name->value(),
              'message' => $notif_wr->field_qn_notification->value(),
            ];
            $notification .=  '<strong>' . $notif_wr->field_qn_produce_unit->name->value() . '</strong>. ' . $notif_wr->field_qn_notification->value() . '<br />';
          }
        }

        if ($query_wr->field_query_type->value() == 'correction') {
          $params['text'] .= 'Номер заявки: ' . $query_wr->getIdentifier() . '<br />' .
            'Месяц: ' . date('F', $query_wr->field_month->value()) . '<br />' .
            'Продукт: ' . $query_wr->field_nomenklatura->name->value() . '<br />' .
            'Количество: ' . $query_wr->field_qty->value() .  '<br />' .
            ($query_wr->field_query_reason->value() ? 'Причина: ' . $query_wr->field_query_reason->name->value() . '<br />' : '') .
            ($query_wr->field_comment->value() ? 'Комментарий: ' . $query_wr->field_comment->value() . '<br />' : '') .
            $notification .
            '<br />';
        } elseif ($query_wr->field_query_type->value() == 'main') {
          if ($query_wr->field_query_status_client->value() == 'approved' && !$main_plan_flag) {
            // основной план
            $params['text'] .= 'Внесён основной план на ' . date('F', $query_wr->field_month->value()) . ' месяц.' . '<br />' .
              '<br />';
            $main_plan_flag = true;
          } elseif ($query_wr->field_query_status_client->value() == 'processing' && !$pred_plan_flag) {
            // предварительный план
            $params['text'] .= 'Внесён/изменён предварительный план на ' . date('F', $query_wr->field_month->value()) . ' месяц.' . '<br />' .
              '<br />';
            $pred_plan_flag = true;
          }
        }
      }

      if ($users = ext_user_get_managers_by_company_uid($value['company_uid'])) {
        foreach ($users as $manager_account) {
          if (!empty($manager_account->field_notify_once_a_day["und"][0]["value"])) {
            $params['mail'] = $manager_account->mail;
            $mail_queue->createItem($params);
          }
        }
      }
    }
  }
}
