<?

define('MANAGER_EMAIL', 'mega_comp@mail.ru');
define('TEST_USER_EMAIL', 'mega_comp@mail.ru');

/**
 * Implements hook_menu()
 */
function mailer_menu()
{
  $items['services/handling-notify/%'] = [
    'page callback' => 'mailer_handling_notify',
    'page arguments' => [2],
    'access callback' => true,
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

function mailer_handling_notify($qid)
{
  $query_wr = entity_metadata_wrapper('query', $qid);

  $account = user_load($query_wr->uid->value());
  $params['qid'] = $qid;
  $params['status'] = $query_wr->field_query_status->name->value();
  $params['comment'] = $query_wr->field_comment->value();
  $params['product'] = $query_wr->field_product->value();
  drupal_mail('mailer', 'user_notify_query_handling', TEST_USER_EMAIL, user_preferred_language($account), $params);

  drupal_set_message('Уведомление по заявке ' . $params['qid'] . ' отправлено на E-Mail');
  drupal_goto($_GET['destination']);
}

/**
 * Implements hook_mail
 */
function mailer_mail($key, &$message, $params)
{
  switch($key) {
    case 'manager_notify_new_query':
      $message['subject'] = 'Новая заявка на производство';

      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>Новая заявка на производство:</p>' .
        'Номер: ' . $params["qid"] . '<br />' .
        'Период: ' . $params["period"]["value"] . ' - ' . $params["period"]["value2"] . '<br />' .
        'Продукт: ' . $params["product"] .  '<br />' .
        'Страна: ' . $params["country"] .  '<br />' .
        'Упаковка: ' . $params['package'] . '<br />' .
        'Количество: ' . $params["qty"] .
        '<p>Перейти к заявкам в <a href="' . url('<front>', ['absolute' => true]) . '">Личный кабинет</a></p>';

      break;

    case 'user_notify_query_handling':
      $message['subject'] = 'Статус заявки на производство изменился';

      $message['body'][] =
        '<h2>Здравствуйте!</h2>' .
        '<p>Вы оставили заявку на производство ' . $params['product'] . ' на сайте компании ООО "Кирово-Чепецкий завод Агрохимикат"</p>' .
        '<p>' .
        'Текущий статус заявки №' . $params['qid'] . ': ' . $params['status'] .
        ($params['comment'] ? '<br />Комментарий: ' . $params['comment'] : $params['comment']) .
        '</p>' .
        '<p>Состояние всех заявок можно посмотреть в <a href="' . url('<front>', ['absolute' => true]) . '">Личном кабинете</a></p>';

      break;
  }
}
