<?

define('DAYS_BEFORE_PRODUCE_START', 1);
// Кол-во дней, которое начиная с текущей даты установка недоступна
// для выбора дат производства.
// Время нужно для согласования и подготовки установки к началу производства.
define('DAYS_UNAVAILABLE', 3);

// tid технических работ
define('TID_SERVICE_WORK', 583);

/**
 * Implementation of hook_menu().
 */
function production_menu()
{
  $items['production/import/buzy'] = array(
    'page callback' => 'production_buzy_import',
    'access callback' => true,
    'file' => 'includes/production.import.inc',
    'type' => MENU_CALLBACK,
  );
  $items['production/import/plan'] = array(
    'page callback' => 'production_plan_import',
    'access callback' => true,
    'file' => 'includes/production.import.inc',
    'type' => MENU_CALLBACK,
  );
  $items['production/import/other'] = array(
    'page callback' => 'production_other_import',
    'access callback' => true,
    'file' => 'includes/production.import.inc',
    'type' => MENU_CALLBACK,
  );

  $items['production/plan/delete'] = array(
    'page callback' => 'production_plan_delete',
    'access callback' => true,
    'file' => 'includes/production.import.inc',
    'type' => MENU_CALLBACK,
  );

  $items['production/plan/%/approve'] = array(
    'page callback' => 'production_plan_approve_callback',
    'page arguments' => [2],
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['production/%/approve'] = array(
    'page callback' => 'production_query_approve_callback',
    'page arguments' => [1],
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/custom/exchange'] = array(
    'title' => 'Импорт',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('production_import_form'),
    'access arguments' => array('access manager settings'),
    'file' => 'includes/production.import.inc',
//    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/config/custom/delete'] = array(
    'title' => 'Удаление заявок',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('production_delete_form'),
    'access arguments' => array('access manager settings'),
    'file' => 'includes/production.import.inc',
//    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_menu_alter().
 */
function production_menu_alter(&$items)
{
  // убрать материалы с Главной
  $items['node']['page callback'] = 'production_empty_front_page_callback';

  // "Удалить" в локальные задачи материала
  // http://xandeadx.ru/blog/drupal/339
  $items['node/%node/delete']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
}

/**
 * Implements hook_cron()
 */
function production_cron()
{
  // выполнить импорт заявок
  if (variable_get('import_pr_1с_enable', 0)) {
    production_process_incoming_files();
  }

  // однократно после восьми отправить письмо с изменениями (при пятиминутном интервале крона)
  // todo кривое решение, может не сработать если сервер не дёрнет крон в этот промежуток
  if (REQUEST_TIME >= strtotime('07:27') && REQUEST_TIME < strtotime('07:34')) {
    mailer_batch_mail_production();
  }
}

/**
 * menu callback
 * убрать материалы с главной
 */
function production_empty_front_page_callback()
{
  drupal_set_title('');
  return [];
}


/**
 * Implements hook_field_placeholder_info().
 */
function production_field_placeholder_info()
{
  // добавить поддержку виджета masked_input в модуле Field Placeholder
  return array(
    'masked_input' => 'value',
  );
}

/**
 * hook_form_FORM_ID_alter
 */
function production_form_alter(&$form, &$form_state, $form_id)
{
  if (!user_has_role(ROLE_ADMIN) && $form_id == 'views_exposed_form' && !empty($form["field_nomenklatura_target_id_selective"])) {
    $tids = array_keys($form["field_nomenklatura_target_id_selective"]["#options"]);
    array_shift($tids);
    if ($terms = entity_load('taxonomy_term', $tids)) {
      foreach($form["field_nomenklatura_target_id_selective"]["#options"] as $tid => &$name) {
        if (!empty($terms[$tid])) {
          $name_arr = [];
          if (!empty($terms[$tid]->field_oc_artikul_davalec["und"][0]["value"])) {
            $name_arr[] = $terms[$tid]->field_oc_artikul_davalec["und"][0]["value"];
          }
          $name_arr[] = !empty($terms[$tid]->field_oc_name_davalec["und"][0]["value"]) ? $terms[$tid]->field_oc_name_davalec["und"][0]["value"] : $name;
          $name = implode(' ', $name_arr);
        }
      }
    }
  }

  if ($form_id == 'eck__entity__form_add_query_query' && !user_has_role(ROLE_ADMIN)) {
    if (!empty($_GET['type'])) {
      $form_state['data']['query']['type'] = $_GET['type'];
    }

    $form_state['data']['davalec_uid'] = $GLOBALS['user']->uid;

    $filter = [];
    if (!empty($_SESSION["views"]["queries"]["default"]["field_month_value"]["value"]["month"])) {
      $filter = $_SESSION["views"]["queries"]["default"]["field_month_value"]["value"];
      $form_state['data']['filter'] = $filter;
    }

    // получить Запрос с которого сделана Корректировка
    if (!empty($_GET['last_query_id'])) {
      $last_query_wr = entity_metadata_wrapper('query', $_GET['last_query_id']);
      $form_state['data']['month_start'] = $last_query_wr->field_month->value();
      $form_state['data']['nom_tid'] = $last_query_wr->field_nomenklatura->tid->value();
      $form_state['data']['last_query'] = [
        'id' => $last_query_wr->getIdentifier(),
        'type' => $last_query_wr->field_query_type->value(),
        'volume' => $last_query_wr->field_qty->value(),
      ];
    }

    // получить Запрос, в котором есть Загрузка
    if (!empty($form_state['data']['last_query']['volume']) && !empty($form_state['data']['nom_tid']) && !empty($form_state['data']['month_start'])) {
      $dbr = db_select('eck_query', 'q');
      $dbr->addField('q', 'id');
      $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
      $dbr->condition('fm.field_month_value', $form_state['data']['month_start']);
      $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
      $dbr->condition('fn.field_nomenklatura_target_id', $form_state['data']['nom_tid']);
      $dbr->innerJoin('field_data_field_load', 'fl', 'fl.entity_id = q.id');
      $dbr->orderBy('q.id','DESC');
      $dbr->range(0,1);
      if ($eck_source = $dbr->execute()->fetchField()) {
        $source_query_wr = entity_metadata_wrapper('query', $eck_source);
        $load = [];
        $date_start = $date_end = 0;
        foreach ($source_query_wr->field_load->getIterator() as $load_wr) {
          if ($load_wr->value()) {
            $load[$load_wr->field_produce_date->value()] = $load_wr->field_produce_output->value();
            if ($load_wr->field_produce_output->value()) {
              if (!$date_start || $date_start > $load_wr->field_produce_date->value()) $date_start = $load_wr->field_produce_date->value();
              if ($date_end < $load_wr->field_produce_date->value()) $date_end = $load_wr->field_produce_date->value();
            }
          }
        }
        $form_state['data']['source_query'] = [
          'id' => $source_query_wr->getIdentifier(),
          'type' => $source_query_wr->field_query_type->value(),
          'volume' => $source_query_wr->field_qty->value(),
          'date_start' => $date_start,
          'date_end' => $date_end,
          'load' => $load,
        ];
      }
    }

    $form["field_query_type"]["und"]["#default_value"][0] = 'correction';
    drupal_set_title('Заявка на производство');

    if (!empty($form_state['data']['query']['type'])) {
      if ($form_state['data']['query']['type'] == 'correction') {
        drupal_set_title('Корректирующая заявка');
        $form["field_query_type"]["und"]["#default_value"][0] = 'correction';
      }

      if (user_has_role(ROLE_MANAGER_PRODUCTION)) {
        $form["field_query_status_client"]["und"]["#default_value"][0] = 'processing';
        $form["field_query_status_manager"]["und"]["#default_value"][0] = 'approved';
        $form["field_query_status_manager"]['#access'] = false;
      } else {
        $form["field_query_status_client"]["und"]["#default_value"][0] = 'approved';
        $form["field_query_status_manager"]["und"]["#default_value"][0] = 'processing';
      }
    }

    // если задан исходный Запрос
    // задать дефолтные значения
    if (!empty($form_state['data']['last_query']['volume'])) {
      $form['old_qty'] = [
        '#type' => 'item',
        '#title' => 'Утверждённое количество',
        '#markup' => '<div class ="form-markup">' . number_format($form_state['data']['last_query']['volume'], 0, '', ' ') . '</div>',
        '#wrapper_attributes' => ['class' => ['field-name-old-qty']],
        '#weight' => 2,
      ];
      $form["field_qty"]["und"][0]["value"]["#title"] = 'Новое количество';
      $form["field_qty"]["und"][0]["value"]["#default_value"] = $form_state['data']['last_query']['volume'];
    }

    // Даты
    if (!empty($form_state['data']['month_start'])) {
      $form["field_month"]["und"][0]["#default_value"]["value"] = $form_state['data']['month_start'];
      $form["field_month"]["und"][0]["#default_value"]["value2"] = $form_state['data']['month_start'];
      $form["field_month"]["und"][0]["#value"]["value"] = $form_state['data']['month_start'];
      $form["field_month"]["und"][0]["#value"]["value2"] = $form_state['data']['month_start'];
    }
    if (empty($form_state["data"]["source_query"]["date_start"]) || empty($form_state["data"]["source_query"]["date_end"])) {
      if ($filter && $filter['month'] && $filter['month'] != date('n')) {
        $day_start = gmmktime(0, 0, 0, $filter['month'], 1, $filter['year']);
        $next_month_start = gmmktime(0, 0, 0, date('n', $day_start) + 1, 1, date('Y', $day_start));
      } else {
        $day_start = gmmktime(0, 0, 0, date('n'), date('j')+1, date('Y'));
        $next_month_start = gmmktime(0, 0, 0, date('n', $day_start) + 1, 1, date('Y', $day_start));
      }
      $form["field_query_period"]["und"][0]["#default_value"]["value"] = $day_start;
      $form["field_query_period"]["und"][0]["#default_value"]["value2"] = $next_month_start-24*3600;
    } else {
      $day_start_start = $form_state['data']['source_query']['date_start'];
      $day_end_start = $form_state['data']['source_query']['date_end'];
      $today_start = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));
      if ($day_start_start <= $today_start) {
        $day_start_start = gmmktime(0, 0, 0, date('n'), date('j')+1, date('Y'));
        if (date('j', $day_end_start) <= date('j')) {
          $day_end_start = gmmktime(0, 0, 0, date('n'), 31, date('Y'));
        }
      }
      $form["field_query_period"]["und"][0]["#default_value"]["value"] = $day_start_start;
      $form["field_query_period"]["und"][0]["#default_value"]["value2"] = $day_end_start;
    }

    if (!empty($form_state['data']['nom_tid'])) {
      $form["field_nomenklatura"]["und"]["#default_value"] = [$form_state['data']['nom_tid']];
    }

  }


  if (in_array($form_id, ['eck__entity__form_add_query_query', 'eck__entity__form_edit_query_query']) && !user_has_role(ROLE_ADMIN)) {
    if (!isset($nomenklatura_from_queries)) $nomenklatura_from_queries = [];
    $produce_units_list = production_produce_units_get_list();

    // обработать кнопку добавления Установки
    if (isset($form_state["triggering_element"]) && $form_state["triggering_element"]["#name"] == 'pu_add' && isset($form_state['values']['pu_select'])) {
      $form_state['data']['produce_units'][$form_state['values']['pu_select']] = [
        'tid' => $form_state['values']['pu_select'],
        'name' => $produce_units_list[$form_state['values']['pu_select']]->name,
        'performance' => null,
      ];
    }

    $form["field_qty"]["#weight"] = 3;
    $form["field_query_period"]["#weight"] = 5;

    if (!user_has_role(ROLE_ADMIN)) {
      $form["field_oc_id"]["#access"] = false;
      $form["field_load"]["#access"] = false;
      $form["field_query_type"]["#access"] = false;
      $form["field_query_notifications"]["#access"] = false;
      $form["field_query_status_client"]["#access"] = false;
      $form["field_query_status_manager"]["und"]["#title"] = 'Статус заявки';
      $form["actions"]["submit"]["#value"] = 'Сохранить и отправить';

      if (!empty($form_state['data']['last_query']['id'])) {
        $form["field_nomenklatura"]['#disabled'] = true;
        $form["field_month"]['#disabled'] = true;
      } else {
        $form["field_month"]['#access'] = false;
        $form["field_query_period"]["#weight"] = 0;
      }

      if ($form["field_query_type"]["und"]["#default_value"][0] == 'cancel') {
        $form["field_qty"]['#disabled'] = true;
        $form["actions"]["submit"]["#attributes"]['class'][] = 'btn-danger';
        $form["actions"]["submit"]["#value"] = 'Отменить производство';
      }

      // если Заявка создана клиентом, то менеджеру не показывать причину и необходимость согласования
      if ((!empty($form_state["query"]->is_new) && !user_has_role(ROLE_MANAGER_PRODUCTION))
        || empty($form_state["query"]->is_new) && !user_has_role(ROLE_MANAGER_PRODUCTION, user_load($form_state["query"]->uid))) {
        $form["field_query_reason"]["#access"] = false;
        $form["field_query_client_approve"]["#access"] = false;
      }

      // ограничить возможности клиентов
      if (!user_has_role(ROLE_MANAGER_PRODUCTION, $GLOBALS['user'])) {
        $form["field_query_status_manager"]["#access"] = false;
        $form["field_query_client_approve"]["#access"] = false;
        $form["field_query_client_approve"]["und"]["#default_value"] = 1;
        // для клиента причина - по инициативе заказчика
        $form["field_query_reason"]["#access"] = false;
        $form["field_query_reason"]["und"]["#default_value"] = [553];

        // ограничить Номенклатуру текущим юзером
        $user_wr = entity_metadata_wrapper('user', $GLOBALS['user']->uid);
        $company_id = $user_wr->field_company->getIdentifier();
        $query = new EntityFieldQuery();
        $result = $query
          ->entityCondition('entity_type', 'taxonomy_term')
          ->propertyCondition('vid', taxonomy_vocabulary_machine_name_load('nomenklatura')->vid)
          ->fieldCondition('field_user', 'target_id', $company_id)
          ->execute();
        if ($result) {
          $nomenklatura_all = entity_load('taxonomy_term', array_keys($result['taxonomy_term']));

          $options = [];
          foreach ($nomenklatura_all as $nomenklatura_term) {
            if (!empty($form["field_nomenklatura"]["und"]["#options"][$nomenklatura_term->tid])
              && strpos($form["field_nomenklatura"]["und"]["#options"][$nomenklatura_term->tid], '_') !== 0) {

              // при добавлении новой Заявки исключить Номенклатуру, по которой есть Заявки
              if (empty($form_state['data']['last_query']) && in_array($nomenklatura_term->tid, $nomenklatura_from_queries)) continue;
              // у клиентов своё наименование
              $name_arr = [];
              if (!empty($nomenklatura_term->field_oc_artikul_davalec["und"][0]["value"])) {
                $name_arr[] = $nomenklatura_term->field_oc_artikul_davalec["und"][0]["value"];
              }
              $name_arr[] = !empty($nomenklatura_term->field_oc_name_davalec["und"][0]["value"]) ? $nomenklatura_term->field_oc_name_davalec["und"][0]["value"] : $form["field_nomenklatura"]["und"]["#options"][$nomenklatura_term->tid];
              $options[$nomenklatura_term->tid] = implode(' ', $name_arr);
            }
          }
          if ($options) {
            $form["field_nomenklatura"]["und"]["#options"] = $options;
            if (!$form["field_nomenklatura"]["und"]["#default_value"] || empty($options[current($form["field_nomenklatura"]["und"]["#default_value"])])) {
              $form["field_nomenklatura"]["und"]["#default_value"] = [array_key_first($options)];
            }
          }
        }
      } else {
        // убрать для менеджера причины Клиента
        unset($form["field_query_reason"]["und"]["#options"][553]);
      }
    }

    $form['#attributes']['class'] = ['query-form'];

    if (empty($form_state['data'])) $form_state['data'] = [];

    if (empty($form_state["query"]->is_new)) {
      $query_wr = entity_metadata_wrapper('query', $form_state["query"]);
      $form_state['data']['query']['id'] = $query_wr->getIdentifier();
      $form_state['data']['query']['volume'] = $query_wr->field_qty->value();
    }

    $month_start = empty($form_state['data']['month_start']) ? 0 : $form_state['data']['month_start'];

    // текущую Загрузку извлекаем:
    // - для новой Заявки из предыдущей Заявки с заданной Загрузкой (если есть)
    // - для редактируемой - из неё самой
    $load_query_id = null;
    if (!empty($form_state['data']['query']['id'])) {
      $load_query_id = $form_state['data']['query']['id'];
    } elseif(!empty($form_state['data']['source_query']['id'])) {
      $load_query_id = $form_state['data']['source_query']['id'];
    }
    if ($load_query_id) {
      $load_query_wr = entity_metadata_wrapper('query', $load_query_id);
      if ($load_query_id && $load_query_wr->value()) {
        $nom_tid = null;
        if ($load_query_wr->field_nomenklatura->value()) {
          $nom_tid = $load_query_wr->field_nomenklatura->tid->value();
        } else {
          $nom_tid = empty($form["field_nomenklatura"]["und"]["#default_value"][0]) ? array_key_first($form["field_nomenklatura"]["und"]["#options"]) : $form["field_nomenklatura"]["und"]["#default_value"][0];
        }

        if ($form["field_query_type"]["und"]["#default_value"][0] != 'cancel') {
          if ($nom_tid) {
            // получить Установки, уже выбранные в данной форме
            $produce_units = empty($form_state['data']['produce_units']) ? [] : $form_state['data']['produce_units'];

            // получить Установки и их Загрузку из Запроса
            $load_produce_units = production_produce_units_get_from_query($load_query_wr->value());
            foreach($load_produce_units as $pu_tid => $pu_item) {
              if (empty($produce_units[$pu_tid])) $produce_units[$pu_tid] = $pu_item;
            }

            $form_state['data']['produce_units'] = $produce_units;
          }
        }
      }
    }


    // добавить в форму установки ------------------------------------------------------------------------------------
    $produce_units = empty($form_state['data']['produce_units']) ? [] : $form_state['data']['produce_units'];

    if ($produce_units) {
      $form['produce_units'] = [
        '#type' => 'container',
        '#attributes' => [
          'id' => ['produce-units-wrapper'],
          'class' => ['produce-units-wrapper'],
        ],
        '#weight' => 6,
      ];

      foreach ($produce_units as $pu_tid => $produce_unit) {
        $produce_unit_load = production_produce_unit_get_load($pu_tid, $month_start, null, $load_query_id);

        $form['produce_units']['pu_' . $pu_tid] = [
          '#type' => 'container',
          '#attributes' => ['class' => ['produce-unit']],
          '#weight' => 3,
        ];
        $form['produce_units']['pu_' . $pu_tid]['name'] = [
          '#type' => 'item',
          '#title' => 'Установка',
          '#markup' => '<h3>' . $produce_unit['name'] . '</h3>',
          '#wrapper_attributes' => ['class' => ['produce-unit-name']],
        ];

        $form['produce_units']['pu_' . $pu_tid]['selection'] = [
          '#type' => 'container',
          '#attributes' => ['class' => ['produce-unit-dates', 'form-item']],
        ];
        $form['produce_units']['pu_' . $pu_tid]['selection']['title'] = [
          '#markup' => '<label class="control-label">Даты</label>',
        ];

        $form['produce_units']['pu_' . $pu_tid]['selection']['dates'] = [
          '#type' => 'container',
          '#attributes' => ['class' => ['form-checkboxes']],
          '#suffix' => '<div class="produce-unit-legenda"><span></span>- установка свободна <span class="unavailable"></span>- установка недоступна <span class="loaded"></span>- установка занята <span class="selected"></span>- выбранные даты</div>',
        ];

        // цикл по количеству дней в месяце
        for ($i = 1; $i <= date("t", $month_start); $i++) {
          $day_start = $month_start + ($i - 1) * 60 * 60 * 24;

          $produce_unit_is_busy = !empty($produce_unit_load[$day_start]['is_busy']);
          $produce_unit_has_current_load = (int)!empty($produce_unit_load[$day_start]['is_current_load']);
          $produce_unit_is_unavailable = (int)!empty($produce_unit_load[$day_start]['is_unavailable']);
          $classes = empty($produce_unit_load[$day_start]['classes']) ? [] : $produce_unit_load[$day_start]['classes'];

          // вывести подсказку при наведении с выходом продукции в этот день
          $tooltip = empty($produce_unit_load[$day_start]['is_current_load']) ? '' : ' data-toggle="tooltip" data-placement="top" title="' . $produce_unit_load[$day_start]['output'] . '"';

          // при создании заявки даты можно выбирать, при редактировании нет
          if (!empty($form_state['query']->is_new) && user_has_role(ROLE_MANAGER_PRODUCTION)) {
            $form['produce_units']['pu_' . $pu_tid]['selection']['dates']['check_' . $pu_tid . '_' . $i] = [
              '#type' => 'checkbox',
              '#title' => '<span>' . $i . '</span>',
              '#disabled' => ($produce_unit_is_busy && !$produce_unit_has_current_load) || ($produce_unit_is_unavailable && !user_has_role(ROLE_MANAGER_PRODUCTION)),
              '#default_value' => $produce_unit_has_current_load,
              '#attributes' => ['class' => $classes],
            ];
            if ($tooltip) {
              $form['produce_units']['pu_' . $pu_tid]['selection']['dates']['check_' . $pu_tid . '_' . $i]['#wrapper_attributes'] = [
                'data-toggle' => 'tooltip',
                'data-placement' => 'top',
                'title' => empty($produce_unit_load[$day_start]['is_current_load']) ? '' : $produce_unit_load[$day_start]['output'],
              ];
            }
          } else {
            $form['produce_units']['pu_' . $pu_tid]['selection']['dates']['check_' . $pu_tid . '_' . $i]['#markup'] = '<span class="c-box ' . implode(' ', $classes) . '"' . $tooltip . '>' . $i . '</span>';
          }
        }

        // производительность
        $form['produce_units']['pu_' . $pu_tid]['performance_' . $pu_tid] = [
          '#type' => 'textfield',
          '#title' => 'Производительность',
          '#required' => true,
          '#access' => user_has_role(ROLE_MANAGER_PRODUCTION),
          '#default_value' => empty($produce_unit['performance']) ? 0 : $produce_unit['performance'],
          '#wrapper_attributes' => ['class' => ['produce-unit-performance']],
        ];

      }
    }

    $form["field_comment"]["und"][0]["value"]["#required"] = !user_has_role(ROLE_MANAGER_PRODUCTION);

    $form["#validate"][] = 'production_form_eck__entity__form_query_query_validate';
    $form["#submit"][] = 'production_form_eck__entity__form_query_query_submit';
    $form["actions"]["submit"]["#name"] = 'eck_submit';
  }

  // дополнительный обработчик сабмита
  if (in_array($form_id, ['eck__entity__form_add_query_query', 'eck__entity__form_edit_query_query'])
      || ($form_id == 'eck__entity__delete_form' && $form["entity"]["#value"]->type == 'query')) {
    $form["#submit"][] = 'production_form_redirect_submit';
  }
}

function production_form_produce_unit_add_ajax_callback($form, &$form_state)
{
  return $form;
}

/**
 * production_form_eck__entity__form validate callback
 */
function production_form_eck__entity__form_query_query_validate(&$form, &$form_state)
{
  if ($form_state["triggering_element"]["#name"] == 'eck_submit') {
    // обычно месяц задан и не доступен для смены
    if (empty($form_state['data']['month_start'])) {
      $month_value = $form_state["values"]["field_query_period"]["und"][0]["value"];
    } else {
      $month_value = $form_state['data']['month_start'];
    }
    $month_start = gmmktime(0, 0, 0, date('n', $month_value), 1, date('Y', $month_value));
    $form_state["values"]["field_month"]["und"][0]["value"] = $month_start;
    $form_state["values"]["field_month"]["und"][0]["value2"] = $month_start;

    // проконтролировать, что период задан в рамках текущего месяца и не ранее сегодня
    if (!user_has_role(ROLE_MANAGER_PRODUCTION) && !user_has_role(ROLE_ADMIN)) {
      $next_day_start = gmmktime(0, 0, 0, date('n'), date('j')+1, date('Y'));
      $period_start = $form_state["values"]["field_query_period"]["und"][0]["value"];
      $period_end = $form_state["values"]["field_query_period"]["und"][0]["value2"];
      $next_month_period_start = gmmktime(0, 0, 0, date('n', $period_start) + 1, 1, date('Y', $period_start));
      if ($period_start < $next_day_start) {
        form_set_error('field_query_period', 'Дата не может быть задана ранее, чем завтра.');
        return false;
      }
      if ($period_end >= $next_month_period_start) {
        form_set_error('field_query_period', 'Конечная дата выходит за рамки одного месяца.');
        return false;
      }
    }

    // Номенклатура Пользователя из Заявок текущего Месяца
    // чтобы исколючить выбор Номенклатуры по которой есть Заявки
    if (empty($form_state["data"]["nom_tid"]) && !empty($form_state['data']['davalec_uid'])) {
      $dbr = db_select('eck_query', 'q');
      $dbr->addField('q', 'id');
      $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
      $dbr->condition('fn.field_nomenklatura_target_id', $form_state["values"]["field_nomenklatura"]["und"][0]["target_id"]);
      $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
      $dbr->condition('fm.field_month_value', $month_start);
      if ($dbr->execute()->fetchCol()) {
        form_set_error('field_nomenklatura', 'По данному наименованию уже есть заявки на заданный месяц. Для внесения правок воспользуйтесь кнопкой "Создать корректировку".');
        return false;
      }
    }

    // если заданы даты для Установки, сохранить их и проверить наличие Производительности
    if (isset($form_state["data"]["produce_units"])) {
      $volume = $form_state["values"]["field_qty"]["und"][0]["value"];
      foreach ($form_state["data"]["produce_units"] as $produce_unit_tid => $produce_unit) {
        $load = [];
        $performance = $form_state['values']['performance_' . $produce_unit_tid] ? $form_state['values']['performance_' . $produce_unit_tid] : 0;
        $form_state["data"]["produce_units"][$produce_unit_tid]['performance'] = $performance;
        if (!$performance) {
          form_set_error('performance_' . $produce_unit_tid, 'Не задана производительность установки');
          return false;
        }
        $today_start = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));

        // посчитать уже произведённое количество
        $output_produced = 0;
        if (!empty($form_state['data']['source_query']['load'])) {
          foreach ($form_state['data']['source_query']['load'] as $load_date => $load_output) {
            if ($load_date <= $today_start) {
              $output_produced += $load_output;
            }
          }
        }
        if ($volume < $output_produced) {
          form_set_error('field_qty', 'Заданное количество меньше уже произведённого.');
          return false;
        }

        // Сформировать Загрузку для выбранной установки.
        // Загрузку с выходом 0 (когда дат задано больше чем хватает Количества) тоже сохраняем,
        // нужна для сравнения старой и заданной Загрузок.
        // Исключим загрузку с 0 на этапе сохранения.
        // Сохранить размеры значений выхода продукции в уже произведённой Загрузке.
        $output_total = 0;
        foreach ($form_state['values'] as $key => $value) {
          if (strpos($key, 'check_' . $produce_unit_tid) === 0 && $value === 1) {
            $day = str_replace('check_' . $produce_unit_tid . '_', '', $key);
            $day_start = $month_start + ($day - 1) * 60 * 60 * 24;
            // вычислить выход на день (Производительность или Остаток)
            // если Загрузка этого дня уже произведена, взять выход из неё (в последнем дне может быть меньше)
            if ($day_start <= $today_start                                                            // в день Заявки Загрузка считается произведённой
              && !empty($form_state['data']['source_query']['load'][$day_start])) {
              $output = $form_state['data']['source_query']['load'][$day_start];
            } else {
              $output = $volume - $output_total >= $performance ? $performance : $volume - $output_total;
            }
            if ($output < 0) $output = 0;
            $output_total += $output;

            $load[] = [
              'field_produce_unit' => $produce_unit_tid,
              'field_produce_date' => $day_start,
              'field_produce_output' => $output,
            ];
          }
        }
        $form_state["data"]["produce_units"][$produce_unit_tid]['load'] = $load;
      }
    }
  }
}

/**
 * production_form_eck__entity__form submi callback
 */
function production_form_eck__entity__form_query_query_submit(&$form, &$form_state)
{
  // сохранить Загрузку
  if (!empty($form_state["values"]["entity"]->id) && !empty($form_state["data"]["produce_units"])) {
    foreach($form_state["data"]["produce_units"] as $puid => $produce_unit) {
      if (!empty($produce_unit['load'])) {
        production_query_load_update($form_state["values"]["entity"]->id, $produce_unit['load']);
      }
    }
  }

  // статус старой Заявки изменить на Отказано
  if (!empty($form_state["data"]["last_query"]['id'])) {
    $last_query_wr = entity_metadata_wrapper('query', $form_state['data']['last_query']['id']);
    if ($last_query_wr->field_query_status_manager->value() == 'processing') {
      $last_query_wr->field_query_status_manager = 'deny';
      $last_query_wr->save();
    }
  }

  $query_wr = entity_metadata_wrapper('query', $form_state["values"]["entity"]->id);

  // экспорт новой заявки
  production_query_export($query_wr);

  // отправить email менеджерам
  $params = [
    'qid' => $query_wr->getIdentifier(),
    'month' => date('F', $query_wr->field_month->value()),
    'product' => $query_wr->field_nomenklatura->name->value(),
    'product_owner_account' => $query_wr->field_nomenklatura->field_user->value(),
    'status_client' => $query_wr->field_query_status_client->label(),
    'status_manager' => $query_wr->field_query_status_manager->label(),
    'client_approve' => $query_wr->field_query_client_approve->value(),
    'type' => $query_wr->field_query_type->value(),
    'reason' => $query_wr->field_query_reason->value() ? $query_wr->field_query_reason->name->value() : '',
    'comment' => $query_wr->field_comment->value(),
  ];


  if ($managers = production_get_managers_to_notify()) {
    foreach ($managers as $manager) {
      drupal_mail('mailer', 'manager_notify_query_correction_new', $manager->mail, user_preferred_language($manager), $params);
    }
  }
}

function production_form_redirect_submit(&$form, &$form_state)
{
  if (!user_has_role(ROLE_ADMIN)) {
    $form_state['redirect'] = user_has_role(ROLE_MANAGER_PRODUCTION) ? 'manage' : 'production/queries';
  }
}



function production_get_reason_by_oc_id($oc_id)
{
  $r_vid = taxonomy_vocabulary_machine_name_load('reasons')->vid;
  $query = new EntityFieldQuery();
  $terms = $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $r_vid)
    ->fieldCondition('field_reason_oc_id', 'value', $oc_id)
    ->execute();
  if ($terms) {
    $entities = entity_load('taxonomy_term', [current($terms['taxonomy_term'])->tid]);
  }
  return empty($entities) ? false: current($entities);
}

function production_get_managers_to_notify()
{
  $dbr = db_select('users', 'u');
  $dbr->innerJoin('users_roles', 'ur', 'ur.uid = u.uid');
  $dbr->condition('ur.rid', ROLE_MANAGER_PRODUCTION);
  $dbr->innerJoin('field_data_field_notify_query', 'nq', 'nq.entity_id = u.uid');
  $dbr->condition('nq.field_notify_query_value', 1);
  $dbr->addField('u', 'uid');
  return ($result = $dbr->execute()->fetchCol()) ? user_load_multiple($result, []) : false;
}


function production_get_nomenklatura_by_artikul($articul)
{
  $nom_vid = taxonomy_vocabulary_machine_name_load('nomenklatura')->vid;
  $query = new EntityFieldQuery();
  $terms = $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $nom_vid)
    ->fieldCondition('field_oc_artikul', 'value', $articul)
    ->execute();
  if ($terms) {
    $entities = entity_load('taxonomy_term', [current($terms['taxonomy_term'])->tid]);
  }
  return empty($entities) ? false: current($entities);
}


function production_get_company_id_by_user($user)
{
  if (is_numeric($user)) {
    $user = user_load($user);
  }

  $cid = 0;
  $user_wr = entity_metadata_wrapper('user', $user);
  if ($user_wr->field_company->value()) {
    $cid = $user_wr->field_company->uid->value();
  }
  return $cid;
}

/**
 * Implements hook_entity_delete().
 */
function production_entity_delete($entity, $type)
{
  // при удалении Запроса удалить всю Загрузку
  if (isset($entity->type) && $entity->type == 'query') {
    if (!empty($entity->field_load['und'])) {
      $ids = [];
      foreach ($entity->field_load['und'] as $item) {
        $ids[] = $item['target_id'];
      }
      entity_delete_multiple('load', $ids);
    }
  }
}

function production_get_messages_html($data)
{
  $messages_html = '';
  if ($messages = unserialize($data)) {
    foreach ($messages as $time => $message) {
      $messages_html .=
        '<div>' .
        '<div>' . date('d.m.y h:m', $time) . '</div>' .
        '<div>' . ($message['from'] == 'user' ? '&nbsp;>>&nbsp;' : '&nbsp;<<&nbsp;') . '</div>' .
        '<div>' . $message['message'] . '</div>' .
        '</div>';
    }
  }

  return '<div>' . $messages_html . '</div>';
}


function production_date_select_process_alter(&$element, $form_state, $context)
{
  // заменить короткие месяца на полные
  if (!empty($element["month"]["#options"])) {
    foreach ($element["month"]["#options"] as $key => &$option) {
      $year = $element["year"]["#default_value"];
      if (!empty($form_state["values"]["field_produce_date_value"]["value"]["year"])) {
         $year = $form_state["values"]["field_produce_date_value"]["value"]["year"];
      } elseif (!empty($form_state["values"]["field_month_value"]['year'])) {
        $year = $form_state["values"]["field_month_value"]["value"]["year"];
      }
      if (is_numeric($key)) $option = t(date('F', gmmktime(0, 0, 0, $key, 1, $year)));
    }
  }
}

/**
 * - Query ---------------------------------------------------------------------------------------------------------
 */

/**
 * @param $query_id
 * @param $managers_status - по умолчанию меняем статус менеджера
 * смена статуса Заявки
 */
function production_query_approve($query_id, $managers_status = true)
{
  $query_wr = entity_metadata_wrapper('query', $query_id);
  if ($query_wr->value()) {
    // менеджер или клиент
    if ($managers_status) {
      $query_wr->field_query_status_manager = 'approved';
      $query_wr->save();
    } else {
      // проверка прав
      if ($query_wr->field_nomenklatura->field_user->uid->value() == $GLOBALS['user']->uid) {
        $query_wr->field_query_status_client = 'approved';
        $query_wr->save();
      }
    }
  }

  return true;
}

/**
 * проверка, началось ли производство по Заявке
 * @param $query
 * @return bool
 */
function production_check_query_produce_started($query)
{
  $today_start = gmmktime(0, 0, 0, date('n', time()), date('j', time()), date('Y', time()));
  $query_wr = entity_metadata_wrapper('query', $query);
  foreach ($query_wr->field_load->getIterator() as $load_wr) {
    if ($load_wr->value()) {
      // за сутки до начала производства и позже - производство началось
      if ($today_start > $load_wr->field_produce_date->value() - 24*60*60) {
        return true;
      }
    }
  }

  return false;
}

/**
 * проверка, закончилось ли производство по Заявке (последняя дата считается за окончание)
 * @param $query
 * @return bool
 */
function production_check_query_produce_finished($query)
{
  $today_start = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));
  $query_wr = entity_metadata_wrapper('query', $query);
  $date_start = null;
  foreach ($query_wr->field_load->getIterator() as $load_wr) {
    if ($load_wr->value()) {
      // за сутки до начала производства и позже - производство началось
      $date_start = $load_wr->field_produce_date->value();
      if ($today_start < $date_start) {
        return false;
      }
    }
  }

  return $date_start ? true : false;
}


/**
 * обработчик кновки согласования
 */
function production_query_approve_callback($query_id)
{
  if (is_numeric($query_id)) {
    production_query_approve($query_id, user_has_role(ROLE_MANAGER_PRODUCTION));
    drupal_set_message('Заявка ' . $query_id . (user_has_role(ROLE_MANAGER_PRODUCTION) ? ' утверждена' : ' согласована'));
  } else {
    drupal_set_message('Ошибка при выполнении запроса', 'warning');
  }

  drupal_goto('<front>');
}

function production_query_export($query_wr)
{
  $query_arr = [
    'id' => $query_wr->getIdentifier(),
    'id_1c' => '',
    'created' => date('d.m.Y H:i:s', $query_wr->created->value()),
    'month' => date('d.m.Y', $query_wr->field_month->value()),
    'artikul_1c' => $query_wr->field_nomenklatura->field_oc_artikul->value(),
    'volume' => $query_wr->field_qty->value(),
    'status_manager' => $query_wr->field_query_status_manager->value(),
    'period_begin' => date('d.m.Y', $query_wr->field_query_period->value->value()),
    'period_end' => date('d.m.Y', $query_wr->field_query_period->value2->value()),
    'comment' => $query_wr->field_comment->value(),
    'load' => [],
    'action' => '',
  ];
  if ($query_wr->field_query_reason->value()) {
    $params['reason_1c'] = 'нужен словарь';
  }

  $query_json = drupal_json_encode($query_arr);
  $filename = 'query_export_' . $query_arr['id'] . '.json';
  $directory = 'private://exchange/';
  file_prepare_directory($directory, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS);
  file_unmanaged_save_data($query_json, $directory . $filename, $replace = FILE_EXISTS_RENAME);
}



function production_query_make_copy($source_query)
{
  $query_new = entity_create('query', [
    'type' => 'query',
    'created' => REQUEST_TIME,
    'uid' => 0,
  ]);
  entity_save('query', $query_new);

  $source_query_wr = entity_metadata_wrapper('query', $source_query->id);

  $query_new_wr = entity_metadata_wrapper('query', $query_new);
  $query_new_wr->field_month = $source_query_wr->field_month->value();
  $query_new_wr->field_nomenklatura = $source_query_wr->field_nomenklatura->value();
  $query_new_wr->field_query_type = 'correction';
  $query_new_wr->field_query_status_client = 'approved';
  $query_new_wr->field_query_status_manager = 'approved';
  $query_new_wr->field_qty = $source_query_wr->field_qty->value();
  $query_new_wr->field_query_reason = $source_query_wr->field_query_reason->value();
  $query_new_wr->field_comment = $source_query_wr->field_comment->value();
  $query_new_wr->field_oc_id = $source_query_wr->field_oc_id->value();
  $query_new_wr->field_query_period = ['value' => $source_query_wr->field_query_period->value->value(), 'value2' => $source_query_wr->field_query_period->value2->value()];
  $query_new_wr->field_load_json = $source_query_wr->field_load_json->value();
  $query_new_wr->save();
}

function production_get_query_by_oc_id($oc_id, $month_start)
{
  $efquery = new EntityFieldQuery();
  $result = $efquery
    ->entityCondition('entity_type', 'query')
    ->fieldCondition('field_oc_id', 'value', $oc_id)
    ->fieldCondition('field_month', 'value', $month_start)
    ->execute();
  if ($result) {
    $entities = entity_load('query', [current($result['query'])->id]);
  }
  return empty($entities) ? false: current($entities);
}

/**
 * - Load ---------------------------------------------------------------------------------------------------------
 */

/**
 * обновить Загрузку в Запросе
 */
function production_query_load_update($query_id, $load_array)
{
  $query_wr = entity_metadata_wrapper('query', $query_id);
  if ($query_wr->value()) {
    // удалить старые записи
    $ids = [];
    foreach ($query_wr->field_load->getIterator() as $field_load_wr) {
      $ids[] = $field_load_wr->getIdentifier();
    }
    entity_delete_multiple('load', $ids);
    $query_wr->field_load->set(null);

    // создать новые
    foreach ($load_array as $load_item) {
      $load = entity_create('load', ['type' => 'load']);
      $load_wr = entity_metadata_wrapper('load', $load);
      $load_wr->field_produce_unit = $load_item['field_produce_unit'];
      $load_wr->field_produce_date = $load_item['field_produce_date'];
      $load_wr->field_produce_output = $load_item['field_produce_output'];
      $load_wr->save();
      $query_wr->field_load[] = $load_wr->getIdentifier();
    }

    $query_wr->save();
  }
}



/**
 * - Produce Units ---------------------------------------------------------------------------------------------------------
 */
function production_produce_units_get_list()
{
  $vid = taxonomy_vocabulary_machine_name_load('produce_units')->vid;
  $query = new EntityFieldQuery();
  $terms = $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $vid)
    ->execute();

  if ($terms) {
    $entities = entity_load('taxonomy_term', array_keys($terms['taxonomy_term']));
  }
  return empty($entities) ? false: $entities;
}

/**
 * получить Установки из Запроса
 */
function production_produce_units_get_from_query($query)
{
  $produce_units = [];
  $query_wr = entity_metadata_wrapper('query', $query);
  foreach ($query_wr->field_load->getIterator() as $load_wr) {
    if ($load_wr->value()) {
      $pu_tid = $load_wr->field_produce_unit->tid->value();
      if (empty($produce_units[$pu_tid])) {
        $produce_units[$pu_tid] = [
          'tid' => $pu_tid,
          'name' => $load_wr->field_produce_unit->name->value(),
          'performance' => 0,
        ];
      }

      // определить максимальную производительность Запросе
      if ($produce_units[$pu_tid]['performance'] < $load_wr->field_produce_output->value()) {
        $produce_units[$pu_tid]['performance'] = $load_wr->field_produce_output->value();
      }
    }
  }
  ksort($produce_units);

  return $produce_units;
}


/**
 * Вернуть список Загрузки заданной Установки на заданный месяц
 */
function production_produce_unit_get_load($produce_unit_tid, $month_start, $date = null, $current_query = null)
{
//  $fid = drupal_hash_base64(__FUNCTION__ . $produce_unit_tid . $month_start . ($date ? $date : ''));
//  $load_array = &drupal_static($fid);

  if (!isset($load_array)) {

    // Заявки до Плана не учитываются (статус клиента == "processing")

    // Для последних утверждённых Заявок берём последнюю сервисную Заявку
    // Для арххивных Заявок Загрузку, в том числе сервисную собираем на дату Заявки

    // массив Загрузки по заданной Установке
    $load_array = [];

    // массив Заявок из которых будем брать Загрузку
    $queries = [];

    $is_last_approved_query = false;

    if ($current_query) {
      $current_query_wr = entity_metadata_wrapper('query', $current_query);
      $is_current_query_main = $current_query_wr->field_query_type->value() == 'main';
      $current_query_nom_tid = $current_query_wr->field_nomenklatura->tid->value();

      // является ли текущая Заявка последней утверждённой
      $dbr = db_select('eck_query', 'q');
      $dbr->addField('q', 'id');
      $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
      $dbr->condition('fm.field_month_value', $month_start);
      $dbr->innerJoin('field_data_field_query_type', 'ft', 'ft.entity_id = q.id');
      $dbr->condition('ft.field_query_type_value', 'service', '!=');
      $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
      $dbr->condition('fn.field_nomenklatura_target_id', $current_query_nom_tid);
      $dbr->innerJoin('field_data_field_query_status_client', 'fsc', 'fsc.entity_id = q.id');
      $dbr->condition('fsc.field_query_status_client_value', 'approved');
      $dbr->innerJoin('field_data_field_query_status_manager', 'fsm', 'fsm.entity_id = q.id');
      $dbr->condition('fsm.field_query_status_manager_value', 'approved');
      $dbr->orderBy('q.id', 'DESC');
      $dbr->range(0, 1);
      if ($result = $dbr->execute()->fetchField()) {
        $is_last_approved_query = $result == $current_query_wr->getIdentifier();
      }
    }

    // Номенклатура на какой-либо Установке могла быть запланирована в первых Заявках
    // и отменена или перенесена на другие в последующих.
    // Поэтому выборка последних утверждённых Заявок только по установкам будет неактуальной,
    // так как не учтёт последующие Заявки, где был такой перенос или отмена выпуска.

    // выбираем Номенклатуру, которая планировалась на Установке в заданном Месяце
    // ислючим Номенклатуру сервисных Заявок, так как сервисных Заявок много и в другом запросе выберем одну актуальную
    $dbr = db_select('eck_query', 'q');
    $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
    $dbr->condition('fm.field_month_value', $month_start);
    $dbr->innerJoin('field_data_field_query_status_manager', 'fsm', 'fsm.entity_id = q.id');
    $dbr->condition('fsm.field_query_status_manager_value', 'approved');
    $dbr->innerJoin('field_data_field_load', 'fl', 'fl.entity_id = q.id');
    $dbr->innerJoin('field_data_field_produce_unit', 'fpu', 'fpu.entity_id = fl.field_load_target_id');
    $dbr->condition('fpu.field_produce_unit_tid', $produce_unit_tid);
    $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
    $dbr->condition('fn.field_nomenklatura_target_id', TID_SERVICE_WORK, '!=');
    $dbr->addField('fn', 'field_nomenklatura_target_id', 'nom_tid');
    $dbr->distinct();
    if ($date && !$is_last_approved_query && !$is_current_query_main) {
      $dbr->condition('q.created', $date, '<=');
    }
    if ($nom_tids = $dbr->execute()->fetchCol()) {

      // добавляем ВСЕ утверждённые Заявки (План и Корректировки) для найденной Номенклатуры в заданный Месяц
      //   нужно найти последние (из всех или на дату), но вместо усложнения запроса, потом пройдёмся в цикле по полю created
      // если задана дата и текущая Заявка не последняя утверждённая, то до заданной даты
      $dbr = db_select('eck_query', 'q');
      $dbr->fields('q', ['id', 'created']);
      $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
      $dbr->condition('fm.field_month_value', $month_start);
      $dbr->innerJoin('field_data_field_query_status_manager', 'fsm', 'fsm.entity_id = q.id');
      $dbr->condition('fsm.field_query_status_manager_value', 'approved');
      $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
      $dbr->condition('fn.field_nomenklatura_target_id', $nom_tids, 'IN');
      $dbr->addField('fn', 'field_nomenklatura_target_id', 'nom_tid');
      if ($date && !$is_last_approved_query && !$is_current_query_main) {
        $dbr->condition('q.created', $date, '<=');
      }
      $queries = $dbr->execute()->fetchAllAssoc('id');

      // добавляем последнюю (актуальную) сервисную Заявку
      $dbr = db_select('eck_query', 'q');
      $dbr->fields('q', ['id', 'created']);
      $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
      $dbr->condition('fm.field_month_value', $month_start);
      $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
      $dbr->condition('fn.field_nomenklatura_target_id', TID_SERVICE_WORK);
      $dbr->addField('fn', 'field_nomenklatura_target_id', 'nom_tid');
      if ($date && !$is_last_approved_query) {
        $dbr->condition('q.created', $date, '<=');
      }
      $dbr->orderBy('q.id', 'DESC');
      $dbr->range(0,1);
      if ($service_query = $dbr->execute()->fetchAllAssoc('id')) {
        $service_query = array_shift($service_query);
        $queries[$service_query->id] = $service_query;
      }

      ksort($queries);
    }

    if ($queries) {
      $nom_queries = [];

      // исключить неактуальные Заявки (для которых есть корректировки)
      // (оставляем последнюю утверждённую для Номенклатуры)
      // Заявка на отмену не должна содержать загрузку, так как отсутствие Загрузки и будет отменой

      // массив Номенклатура - Последняя актуальная Заявка
      foreach ($queries as $query_id => $query) {
        if (empty($nom_queries[$query->nom_tid]) || ($nom_queries[$query->nom_tid]['created'] <= $query->created && $nom_queries[$query->nom_tid]['query_id'] < $query_id)) {
          $nom_queries[$query->nom_tid] = [
            'query_id' => $query_id,
            'created' => $query->created,
          ];
        }
      }

      // из актуальных Заявок собираем Загрузку
      foreach ($nom_queries as $nom_tid => $query) {
        $query_wr = entity_metadata_wrapper('query', $query['query_id']);
        foreach ($query_wr->field_load->getIterator() as $load_wr) {
          // в одной Заявке может быть Загрузка с разных установок, отфильтровать

          if ($load_wr->field_produce_unit->value() && $load_wr->field_produce_unit->getIdentifier() == $produce_unit_tid) {
            $day_start = $load_wr->field_produce_date->value();

            $nom_arr = [];
            if ($output = $load_wr->field_produce_output->value()) {
              $nom_arr = [
                'tid' => $nom_tid,
                'produce_date' => $load_wr->field_produce_date->value(),
                'produce_unit' => $load_wr->field_produce_unit->tid->value(),
                'name' => $query_wr->field_nomenklatura->name->value(),
                'artikul_d' => $query_wr->field_nomenklatura->field_oc_artikul_davalec->value(),
                'name_d' => $query_wr->field_nomenklatura->field_oc_name_davalec->value(),
                'client_id' => $load_wr->field_produce_output->value() ? $query_wr->field_nomenklatura->field_user->uid->value() : 0,
              ];
            } elseif ($nom_tid == TID_SERVICE_WORK) {
              $nom_arr = ['tid' => 0, 'client_id' => 0, 'name' => 'Технические работы'];
            }

            if ($nom_arr) {
              $load_array[$day_start] = [
                'output' => $output,
                'nomenklatura' => $nom_arr,
              ];
            }
          }
        }
      }
      ksort($load_array);

      if ($load_array) {

        // если задана текущая Заявка, добавить дополнительные данные
        $current_company_id = production_get_company_id_by_user($GLOBALS['user']);
        if ($current_query) {
          if ($current_nom_tid = $current_query_wr->field_nomenklatura->tid->value()) {
            $current_company_id = $current_query_wr->field_nomenklatura->field_user->uid->value();
            $current_query_type = $current_query_wr->field_query_type->value();

            // is_current_load
            foreach ($current_query_wr->field_load->getIterator() as $current_load_wr) {
              $produce_date = $current_load_wr->field_produce_date->value();
              if (empty($load_array[$produce_date]) && !empty($load_nomenklatura[$current_load_wr->getIdentifier()])
                // данное условие нужно, так как в Заявке может быть 2 и более установки
//                && $current_load_wr->field_produce_unit->tid->value() == $produce_unit_tid
              ) {
                $load_array[$produce_date] = [
                  'output' => $current_load_wr->field_produce_output->value(),
                  'nomenklatura' => $load_nomenklatura[$current_load_wr->getIdentifier()],
                ];
              }
              if ($current_load_wr->field_produce_output->value()
                && isset($load_array[$produce_date]) && $load_array[$produce_date]["nomenklatura"]["tid"] == $current_query_wr->field_nomenklatura->tid->value()) {
                $load_array[$current_load_wr->field_produce_date->value()]['is_current_load'] = true;
              }
            }
          }
        }

        $today_start = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));
        foreach ($load_array as $day_start => $load_array_item) {
          // для текущей Номенклатуры занятость не выводим (в случае заполнения корректирующей Заявки)
          $load_array[$day_start]['is_busy'] = !empty($load_array[$day_start]['nomenklatura']) && isset($current_nom_tid) && $load_array[$day_start]['nomenklatura']['tid'] != $current_nom_tid;
          // дозаполним текущую Загрузку для которой значение false
          $load_array[$day_start]['is_current_load'] = !empty($load_array[$day_start]['is_current_load']);

          // дата недоступна для выбора в корректирующей Заявке для Клиента до сегодня и ещё спустя DAYS_UNAVAILABLE дней
          // данные могут быть получены из начальной и корректирующей Заявок
          $load_array[$day_start]['is_unavailable'] =
            !user_has_role(ROLE_MANAGER_PRODUCTION)
            && ($day_start < $today_start + DAYS_UNAVAILABLE * 24 * 60 * 60)
            && ($current_query && in_array($current_query_type, ['main', 'correction']));

          // загрузка установки этим же клиентом
          $load_array[$day_start]['is_busy_same_company'] = !empty($load_array[$day_start]['nomenklatura']) && isset($current_company_id) && $load_array[$day_start]['nomenklatura']['client_id'] == $current_company_id;

          $classes = [];
          if ($load_array[$day_start]['is_busy_same_company'] && !$load_array[$day_start]['is_current_load']) {
            $classes[] = 'company-loaded';
          } else {
            if ($load_array[$day_start]['is_busy'] && !$load_array[$day_start]['is_current_load']) $classes[] = 'loaded';
          }

//              if ($load_array[$day_start]['is_busy'] && !$load_array[$day_start]['is_current_load']) $classes[] = 'loaded';
          if ($load_array[$day_start]['is_current_load']) $classes[] = 'selected';
          if ($load_array[$day_start]['is_unavailable'] && !$load_array[$day_start]['is_current_load']) $classes[] = 'unavailable';
          $load_array[$day_start]['classes'] = $classes;
        }
      }

    }
  }

  return $load_array;
}

function production_produce_unit_get_load1($produce_unit_tid, $month_start, $date = null, $current_query_id = null)
{
//  $fid = drupal_hash_base64(__FUNCTION__ . $produce_unit_tid . $month_start . ($date ? $date : ''));
//  $load_array = &drupal_static($fid);

  if (!isset($load_array)) {

    // Заявки до Плана не учитываются (статус клиента == "processing")

    // Для последних утверждённых Заявок берём последнюю сервисную Заявку
    // Для арххивных Заявок Загрузку, в том числе сервисную собираем на дату Заявки

    // массив Загрузки по заданной Установке
    $load_array = [];

    // массив Заявок из которых будем брать Загрузку
    $queries = [];
    $is_current_query_main = $is_query_last_approved = false;
    if ($current_query_id) {
      $current_query_wr = entity_metadata_wrapper('query', $current_query_id);
      $is_query_last_approved = _check_query_is_last_approved($current_query_id, $month_start);
      $is_current_query_main = $current_query_wr->field_query_type->value() == 'main';
    }

    // Номенклатура на какой-либо Установке могла быть запланирована в первых Заявках
    // и отменена или перенесена на другие в последующих.
    // Поэтому выборка последних утверждённых Заявок только по установкам будет неактуальной,
    // так как не учтёт последующие Заявки, где был такой перенос или отмена выпуска.

    // выбираем Номенклатуру, которая планировалась на Установке в заданном Месяце
    // ислючим Номенклатуру сервисных Заявок, так как сервисных Заявок много и в другом запросе выберем одну актуальную
    $dbr = db_select('eck_query', 'q');
    $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
    $dbr->condition('fm.field_month_value', $month_start);
    $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
    $dbr->condition('fn.field_nomenklatura_target_id', TID_SERVICE_WORK, '!=');
    $dbr->innerJoin('field_data_field_query_status_manager', 'fsm', 'fsm.entity_id = q.id');
    $dbr->condition('fsm.field_query_status_manager_value', 'approved');
    $dbr->innerJoin('field_data_field_load_json', 'flj', 'flj.entity_id = q.id');
    $dbr->condition('flj.field_load_json_value', '%' . db_like('"pu_tid":"' . $produce_unit_tid . '"') . '%', 'LIKE');
    $dbr->addField('fn', 'field_nomenklatura_target_id', 'nom_tid');
    $dbr->distinct();
    if ($date && !$is_query_last_approved && !$is_current_query_main) {
      $dbr->condition('q.created', $date, '<=');
    }
    if ($nom_tids = $dbr->execute()->fetchCol()) {

      // добавляем ВСЕ утверждённые Заявки (План и Корректировки) для найденной Номенклатуры в заданный Месяц
      //   нужно найти последние (из всех или на дату), но вместо усложнения запроса, потом пройдёмся в цикле по полю created
      // если задана дата и текущая Заявка не последняя утверждённая, то до заданной даты
      $dbr = db_select('eck_query', 'q');
      $dbr->fields('q', ['id', 'created']);
      $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
      $dbr->condition('fm.field_month_value', $month_start);
      $dbr->innerJoin('field_data_field_query_status_manager', 'fsm', 'fsm.entity_id = q.id');
      $dbr->condition('fsm.field_query_status_manager_value', 'approved');
      $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
      $dbr->condition('fn.field_nomenklatura_target_id', $nom_tids, 'IN');
      $dbr->addField('fn', 'field_nomenklatura_target_id', 'nom_tid');
      if ($date && !$is_query_last_approved && !$is_current_query_main) {
        $dbr->condition('q.created', $date, '<=');
      }
      $queries = $dbr->execute()->fetchAllAssoc('id');

      // добавляем последнюю (актуальную) сервисную Заявку
      $dbr = db_select('eck_query', 'q');
      $dbr->fields('q', ['id', 'created']);
      $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
      $dbr->condition('fm.field_month_value', $month_start);
      $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
      $dbr->condition('fn.field_nomenklatura_target_id', TID_SERVICE_WORK);
      $dbr->addField('fn', 'field_nomenklatura_target_id', 'nom_tid');
      if ($date && !$is_query_last_approved) {
        $dbr->condition('q.created', $date, '<=');
      }
      $dbr->orderBy('q.id', 'DESC');
      $dbr->range(0,1);
      if ($service_query = $dbr->execute()->fetchAllAssoc('id')) {
        $service_query = array_shift($service_query);
        $queries[$service_query->id] = $service_query;
      }

      ksort($queries);
    }

    if ($queries) {
      $nom_queries = [];

      // исключить неактуальные Заявки (для которых есть корректировки)
      // (оставляем последнюю утверждённую для Номенклатуры)
      // Заявка на отмену не должна содержать загрузку, так как отсутствие Загрузки и будет отменой

      // массив Номенклатура - Последняя актуальная Заявка
      foreach ($queries as $query_id => $query) {
        if (empty($nom_queries[$query->nom_tid]) || ($nom_queries[$query->nom_tid]['created'] <= $query->created && $nom_queries[$query->nom_tid]['query_id'] < $query_id)) {
          $nom_queries[$query->nom_tid] = [
            'query_id' => $query_id,
            'created' => $query->created,
          ];
        }
      }

      // из актуальных Заявок собираем Загрузку
      foreach ($nom_queries as $nom_tid => $query) {
        $query_wr = entity_metadata_wrapper('query', $query['query_id']);
        if ($query_load = drupal_json_decode($query_wr->field_load_json->value())) {
          foreach ($query_load as $punit_tid => $query_p_unit_load) {
            // в одной Заявке может быть Загрузка с разных установок, отфильтровать

            if ($punit_tid == $produce_unit_tid) {
              $punit_wr = entity_metadata_wrapper('taxonomy_term', $produce_unit_tid);
              foreach ($query_p_unit_load as $load) {
                $day_start = $load['date'];

                $nom_arr = [];
                if ($output = $load['output']) {
                  $nom_arr = [
                    'tid' => $nom_tid,
                    'produce_date' => $load['date'],
                    'produce_unit' => $produce_unit_tid,
                    'name' => $punit_wr->label(),
                    'artikul_d' => $query_wr->field_nomenklatura->field_oc_artikul_davalec->value(),
                    'name_d' => $query_wr->field_nomenklatura->field_oc_name_davalec->value(),
                    'client_id' => $load['output'] ? $query_wr->field_nomenklatura->field_user->uid->value() : 0,
                  ];
                } elseif ($nom_tid == TID_SERVICE_WORK) {
                  $nom_arr = ['tid' => 0, 'client_id' => 0, 'name' => 'Технические работы'];
                }

                if ($nom_arr) {
                  $load_array[$day_start] = [
                    'output' => $output,
                    'nomenklatura' => $nom_arr,
                  ];
                }
              }
            }
          }
        }
      }
      ksort($load_array);

      if ($load_array) {

        // если задана текущая Заявка, добавить дополнительные данные
        $current_company_id = production_get_company_id_by_user($GLOBALS['user']);
        if ($current_query_id) {
          if ($current_nom_tid = $current_query_wr->field_nomenklatura->getIdentifier()) {
            $current_company_id = $current_query_wr->field_nomenklatura->field_user->getIdentifier();
            $current_query_type = $current_query_wr->field_query_type->value();

            // is_current_load
            foreach ($current_query_wr->field_load->getIterator() as $current_load_wr) {
              $produce_date = $current_load_wr->field_produce_date->value();
              if (empty($load_array[$produce_date]) && !empty($load_nomenklatura[$current_load_wr->getIdentifier()])
                // данное условие нужно, так как в Заявке может быть 2 и более установки
//                && $current_load_wr->field_produce_unit->tid->value() == $produce_unit_tid
              ) {
                $load_array[$produce_date] = [
                  'output' => $current_load_wr->field_produce_output->value(),
                  'nomenklatura' => $load_nomenklatura[$current_load_wr->getIdentifier()],
                ];
              }
              if ($current_load_wr->field_produce_output->value()
                && isset($load_array[$produce_date]) && $load_array[$produce_date]["nomenklatura"]["tid"] == $current_query_wr->field_nomenklatura->tid->value()) {
                $load_array[$current_load_wr->field_produce_date->value()]['is_current_load'] = true;
              }
            }
          }
        }

        $today_start = gmmktime(0, 0, 0, date('n'), date('j'), date('Y'));
        foreach ($load_array as $day_start => $load_array_item) {
          // для текущей Номенклатуры занятость не выводим (в случае заполнения корректирующей Заявки)
          $load_array[$day_start]['is_busy'] = !empty($load_array[$day_start]['nomenklatura']) && isset($current_nom_tid) && $load_array[$day_start]['nomenklatura']['tid'] != $current_nom_tid;
          // дозаполним текущую Загрузку для которой значение false
          $load_array[$day_start]['is_current_load'] = !empty($load_array[$day_start]['is_current_load']);

          // дата недоступна для выбора в корректирующей Заявке для Клиента до сегодня и ещё спустя DAYS_UNAVAILABLE дней
          // данные могут быть получены из начальной и корректирующей Заявок
          $load_array[$day_start]['is_unavailable'] =
            !user_has_role(ROLE_MANAGER_PRODUCTION)
            && ($day_start < $today_start + DAYS_UNAVAILABLE * 24 * 60 * 60)
            && ($current_query_id && in_array($current_query_type, ['main', 'correction']));

          // загрузка установки этим же клиентом
          $load_array[$day_start]['is_busy_same_company'] = !empty($load_array[$day_start]['nomenklatura']) && isset($current_company_id) && $load_array[$day_start]['nomenklatura']['client_id'] == $current_company_id;

          $classes = [];
          if ($load_array[$day_start]['is_busy_same_company'] && !$load_array[$day_start]['is_current_load']) {
            $classes[] = 'company-loaded';
          } else {
            if ($load_array[$day_start]['is_busy'] && !$load_array[$day_start]['is_current_load']) $classes[] = 'loaded';
          }

//              if ($load_array[$day_start]['is_busy'] && !$load_array[$day_start]['is_current_load']) $classes[] = 'loaded';
          if ($load_array[$day_start]['is_current_load']) $classes[] = 'selected';
          if ($load_array[$day_start]['is_unavailable'] && !$load_array[$day_start]['is_current_load']) $classes[] = 'unavailable';
          $load_array[$day_start]['classes'] = $classes;
        }
      }

    }
  }

  return $load_array;
}

function _check_query_is_last_approved($query_id, $month_start)
{
  $query_wr = entity_metadata_wrapper('query', $query_id);
  $query_nom_tid = $query_wr->field_nomenklatura->getIdentifier();

  // является ли текущая Заявка последней утверждённой
  $dbr = db_select('eck_query', 'q');
  $dbr->addField('q', 'id');
  $dbr->innerJoin('field_data_field_month', 'fm', 'fm.entity_id = q.id');
  $dbr->condition('fm.field_month_value', $month_start);
  $dbr->innerJoin('field_data_field_query_type', 'ft', 'ft.entity_id = q.id');
  $dbr->condition('ft.field_query_type_value', 'service', '!=');
  $dbr->innerJoin('field_data_field_nomenklatura', 'fn', 'fn.entity_id = q.id');
  $dbr->condition('fn.field_nomenklatura_target_id', $query_nom_tid);
  $dbr->innerJoin('field_data_field_query_status_client', 'fsc', 'fsc.entity_id = q.id');
  $dbr->condition('fsc.field_query_status_client_value', 'approved');
  $dbr->innerJoin('field_data_field_query_status_manager', 'fsm', 'fsm.entity_id = q.id');
  $dbr->condition('fsm.field_query_status_manager_value', 'approved');
  $dbr->orderBy('q.id', 'DESC');
  $dbr->range(0, 1);
  if ($result = $dbr->execute()->fetchField()) {
    return $result == $query_id;
  }
}

function production_get_produce_unit_by_1cID($produce_unit_1cID)
{
  $vid = taxonomy_vocabulary_machine_name_load('produce_units')->vid;
  $query = new EntityFieldQuery();
  $terms = $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $vid)
    ->fieldCondition('field_oc_produce_unit_id', 'value', $produce_unit_1cID)
    ->execute();

  if ($terms) {
    $entities = entity_load('taxonomy_term', [current($terms['taxonomy_term'])->tid]);
  }
  return empty($entities) ? false: current($entities);
}


